"""initial schema

Revision ID: f6958f02df98
Revises: 
Create Date: 2026-05-15 16:00:38.009472
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f6958f02df98'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokerages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.Text(), nullable=False),
    sa.Column('trade_name', sa.Text(), nullable=True),
    sa.Column('primary_license_number', sa.Text(), nullable=True),
    sa.Column('primary_province', sa.Text(), nullable=False),
    sa.Column('head_office_address_raw', sa.Text(), nullable=True),
    sa.Column('phone_e164', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('website_status', sa.Text(), nullable=True),
    sa.Column('website_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('website_relevance_heuristic', sa.Text(), nullable=True),
    sa.Column('google_place_id', sa.Text(), nullable=True),
    sa.Column('google_rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('google_review_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_brokerages_google_place_id', 'brokerages', ['google_place_id'], unique=False)
    op.create_index('ix_brokerages_is_active', 'brokerages', ['is_active'], unique=False)
    op.create_index('ix_brokerages_legal_name_primary_province', 'brokerages', ['legal_name', 'primary_province'], unique=False)
    op.create_index('ix_brokerages_primary_province', 'brokerages', ['primary_province'], unique=False)
    op.create_index('ix_brokerages_website_status', 'brokerages', ['website_status'], unique=False)
    op.create_table('scrape_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_scraped', sa.Integer(), nullable=True),
    sa.Column('records_new', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diff_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scrape_runs_source_started_at', 'scrape_runs', ['source', sa.literal_column('started_at DESC')], unique=False)
    op.create_table('brokers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('designations', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('primary_brokerage_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_brokerage_id'], ['brokerages.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_brokers_canonical_name', 'brokers', ['canonical_name'], unique=False)
    op.create_index('ix_brokers_is_active', 'brokers', ['is_active'], unique=False)
    op.create_index('ix_brokers_primary_brokerage_id', 'brokers', ['primary_brokerage_id'], unique=False)
    op.create_table('broker_licenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('broker_id', sa.UUID(), nullable=False),
    sa.Column('province', sa.Text(), nullable=False),
    sa.Column('license_number', sa.Text(), nullable=False),
    sa.Column('license_tier', sa.Text(), nullable=False),
    sa.Column('license_status', sa.Text(), nullable=False),
    sa.Column('license_issued_date', sa.Date(), nullable=True),
    sa.Column('license_expiry_date', sa.Date(), nullable=True),
    sa.Column('registry_source_url', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('province', 'license_number')
    )
    op.create_index('ix_broker_licenses_broker_id', 'broker_licenses', ['broker_id'], unique=False)
    op.create_index('ix_broker_licenses_is_active', 'broker_licenses', ['is_active'], unique=False)
    op.create_index('ix_broker_licenses_license_expiry_date', 'broker_licenses', ['license_expiry_date'], unique=False)
    op.create_index('ix_broker_licenses_license_status', 'broker_licenses', ['license_status'], unique=False)
    # ### end Alembic commands ###

    # Postgres BEFORE UPDATE trigger to maintain updated_at on raw SQL UPDATEs
    # (bulk upserts, Alembic data migrations, Polars-driven cleaning passes).
    # The ORM onupdate=func.now() hook in models.py is kept as belt-and-suspenders.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER set_updated_at_brokerages "
        "BEFORE UPDATE ON brokerages "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER set_updated_at_brokers "
        "BEFORE UPDATE ON brokers "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER set_updated_at_broker_licenses "
        "BEFORE UPDATE ON broker_licenses "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )


def downgrade() -> None:
    # Drop triggers first (explicit even though drop_table would cascade them),
    # then function after the tables go.
    op.execute("DROP TRIGGER IF EXISTS set_updated_at_broker_licenses ON broker_licenses;")
    op.execute("DROP TRIGGER IF EXISTS set_updated_at_brokers ON brokers;")
    op.execute("DROP TRIGGER IF EXISTS set_updated_at_brokerages ON brokerages;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_broker_licenses_license_status', table_name='broker_licenses')
    op.drop_index('ix_broker_licenses_license_expiry_date', table_name='broker_licenses')
    op.drop_index('ix_broker_licenses_is_active', table_name='broker_licenses')
    op.drop_index('ix_broker_licenses_broker_id', table_name='broker_licenses')
    op.drop_table('broker_licenses')
    op.drop_index('ix_brokers_primary_brokerage_id', table_name='brokers')
    op.drop_index('ix_brokers_is_active', table_name='brokers')
    op.drop_index('ix_brokers_canonical_name', table_name='brokers')
    op.drop_table('brokers')
    op.drop_index('ix_scrape_runs_source_started_at', table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_index('ix_brokerages_website_status', table_name='brokerages')
    op.drop_index('ix_brokerages_primary_province', table_name='brokerages')
    op.drop_index('ix_brokerages_legal_name_primary_province', table_name='brokerages')
    op.drop_index('ix_brokerages_is_active', table_name='brokerages')
    op.drop_index('ix_brokerages_google_place_id', table_name='brokerages')
    op.drop_table('brokerages')
    # ### end Alembic commands ###

    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")
